apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulseguard
resources:
  - namespace.yaml
  - config.yaml
  - kafka.yaml
  - mongodb.yaml
  - topic-init.yaml
  - api.yaml
  - streaming.yaml
  - autoscaling.yaml
  - spark-rbac.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: pulseguard
    includeSelectors: false
