apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-driver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver
rules:
  - apiGroups: [""]
    resources: [pods, services, configmaps, persistentvolumeclaims]
    verbs: [get, list, watch, create, delete, deletecollection, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver
subjects:
  - {kind: ServiceAccount, name: spark-driver, namespace: pulseguard}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-driver
