apiVersion: batch/v1
kind: Job
metadata:
  name: topic-init
spec:
  backoffLimit: 6
  activeDeadlineSeconds: 600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-topics
          image: apache/kafka:3.9.1
          command: [/bin/bash, -ec]
          args:
            - |
              until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list; do sleep 5; done
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic transactions.v1 --partitions 6 --replication-factor 1 --config retention.ms=604800000
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {cpu: 500m, memory: 384Mi}
